version: '3.3'

services:
  db:
    container_name: postgres-container
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ../../configs/docker-psql-conf.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  web_backend:
    image: sergencio/web_backend
    container_name: web-backend-container
    depends_on:
      db:
       condition: service_healthy
    env_file:
      - ../../configs/docker-psql-conf.env
      - ../../configs/docker-gin-conf.env
    restart: always
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local